{{- if .Values.cronJob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  schedule: {{ .Values.cronJob.schedule | default "*/2 * * * *" | quote }}
  suspend: {{ .Values.cronJob.suspend | default false }}
  concurrencyPolicy: {{ .Values.cronJob.concurrencyPolicy | default "Forbid" }}
  successfulJobsHistoryLimit: {{ .Values.cronJob.successfulJobsHistoryLimit | default 3 }}
  failedJobsHistoryLimit: {{ .Values.cronJob.failedJobsHistoryLimit | default 3 }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cronJob.backoffLimit | default 2 }}
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .Release.Name }}
        spec:
          restartPolicy: {{ .Values.cronJob.restartPolicy | default "OnFailure" }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
            env:
              - name: TZ
                value: {{ .Values.timezone | default "Asia/Kolkata" | quote }}
              {{- if .Values.extraEnv }}
              {{- toYaml .Values.extraEnv | nindent 14 }}
              {{- end }}
{{- end }}

